name: cucuEnv
channels:
  - anaconda
  - defaults
dependencies:
  - anaconda-client=1.7.2=py36_0
  - anaconda-navigator=1.9.2=py36_0
  - asn1crypto=0.24.0=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - clyent=1.2.2=py36_1
  - idna=2.7=py36_0
  - jsonschema=2.6.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - nbformat=4.4.0=py36_0
  - psutil=5.4.8=py36h7b6447c_0
  - pycparser=2.19=py36_0
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - qtpy=1.5.2=py36_0
  - requests=2.20.1=py36_0
  - urllib3=1.23=py36_0
  - _tflow_select=2.1.0=gpu
  - absl-py=0.6.1=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - certifi=2018.11.29=py36_0
  - cloudpickle=0.6.1=py36_0
  - cryptography=2.4.1=py36h1ba5d50_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py36_0
  - cython=0.29.2=py36he6710b0_0
  - dask-core=1.0.0=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.12=h23475e2_2
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - html5lib=0.9999999=py36_0
  - icu=58.2=h9c2bf20_1
  - imageio=2.4.1=py36_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.35=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.0=py36h7b6447c_0
  - matplotlib=2.2.2=py36hb69df0a_2
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - nbconvert=5.3.1=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py36_1
  - notebook=5.7.2=py36_0
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1a=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=18.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pygments=2.2.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pyqt=5.6.0=py36h22d08a2_6
  - python=3.6.7=h0371630_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - pywavelets=1.0.1=py36hdd07704_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.6.3=h8bf5577_3
  - qtconsole=4.4.3=py36_0
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.0=py36hf484d3e_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - send2trash=1.5.0=py36_0
  - setuptools=40.6.2=py36_0
  - sip=4.18.1=py36hf484d3e_2
  - six=1.12.0=py36_0
  - sqlite=3.25.3=h7b6447c_0
  - tensorboard=1.7.0=py36hf484d3e_1
  - tensorflow=1.7.0=0
  - tensorflow-base=1.7.0=py36hdbcaa40_2
  - tensorflow-gpu=1.7.0=0
  - tensorflow-gpu-base=1.7.0=py36hcdda91b_1
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - astroid==2.1.0
    - dask==1.0.0
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - pylint==2.2.2
    - typed-ast==1.1.0
    - wrapt==1.10.11
prefix: /home/simon/anaconda3/envs/cucuEnv

